version: '3.1'

services:
  php:
    container_name: todoapp
    build: .
    ports:
      - 4006:80
    volumes:
      - ./:/var/www/html

  db:
    image: mysql
    container_name: todoappdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: run
      MYSQL_DATABASE: mydata
    volumes:
      - todoappvol:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  todoappvol: